/**
 * The main part of the calculator doing the calculations.
 * 
 * @author: Debra Blackman
 * @version January 4, 2016
 */
public class StarWarsName
{
    // Put instance variables here.

    /**
     * Create a StarWarsName object.
     */
    public StarWarsName()
    {
    }
    public String getStarWarsName(String firstName, String lastName, String mothersMaidenName, String placeOfBirth)
    {
       String swname = "";
       swname = lastName.substring(0,3)+firstName.substring(0,2)+" "+mothersMaidenName.substring(0,2)+placeOfBirth.substring(0,3);
       return (swname);
    }
    
  

    /**
     * The getStarWarsName method develops and returns 
     * the Star Wars name given by the formula:
     * 
     *  the first name is the first 3 letters of your last name
     *    concatenated with the first 2 letters of your first name
     *  the last name is the first 2 letters of your mother's maiden name
     *    concatenated with the first 3 letters of your place of birth
     *
     *@param String first name
     *@param String last name
     *@param String mother's maiden name
     *@param String place of birth
     *@return String The Star Wars Name generated by the given rules
     *
     *if an invalid parameter is passed, the method should return
     *the empty string "" and put out an appropriate error message
     *on standard output
     *
     */


    
}
